// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8-JDkOiqJX0AsUCN9WXCaOBpXK95Nf7o',
    appId: '1:88977635857:web:a7093868dd6ed10ed8cfb0',
    messagingSenderId: '88977635857',
    projectId: 'onetrip-999be',
    authDomain: 'onetrip-999be.firebaseapp.com',
    storageBucket: 'onetrip-999be.firebasestorage.app',
    measurementId: 'G-NDVFRWKKT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC_-fc86C3UATDoTkGME0eE6mL9priAkk',
    appId: '1:88977635857:android:2cd27eb536f88865d8cfb0',
    messagingSenderId: '88977635857',
    projectId: 'onetrip-999be',
    storageBucket: 'onetrip-999be.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRjXIH8MEwS02ntKI3KmNgBZWtqEscv_Y',
    appId: '1:88977635857:ios:e0d461bde1627357d8cfb0',
    messagingSenderId: '88977635857',
    projectId: 'onetrip-999be',
    storageBucket: 'onetrip-999be.firebasestorage.app',
    iosClientId: '88977635857-d8huprd0rvic8jamo9p3rff5c9u33rov.apps.googleusercontent.com',
    iosBundleId: 'com.example.oneTrip',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRjXIH8MEwS02ntKI3KmNgBZWtqEscv_Y',
    appId: '1:88977635857:ios:e0d461bde1627357d8cfb0',
    messagingSenderId: '88977635857',
    projectId: 'onetrip-999be',
    storageBucket: 'onetrip-999be.firebasestorage.app',
    iosClientId: '88977635857-d8huprd0rvic8jamo9p3rff5c9u33rov.apps.googleusercontent.com',
    iosBundleId: 'com.example.oneTrip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8-JDkOiqJX0AsUCN9WXCaOBpXK95Nf7o',
    appId: '1:88977635857:web:76003d95abeadd76d8cfb0',
    messagingSenderId: '88977635857',
    projectId: 'onetrip-999be',
    authDomain: 'onetrip-999be.firebaseapp.com',
    storageBucket: 'onetrip-999be.firebasestorage.app',
    measurementId: 'G-Q9V7H88HLE',
  );
}
